version: '3.8'
services: 
  clnkgo:
    build: 
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - ../:/var/dev
    ports:
      - 8000:8000